version: '3.8'

services:
  api:
    build:
      context: ./nodejs-docker
      dockerfile: Dockerfile
    container_name: takijunchik-api
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - DATABASE_HOST=127.0.0.1
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=database_production
    restart: always

  # frontend:
  #   build:
  #     context: ./react-docker
  #     dockerfile: Dockerfile
  #   container_name: takijunchik-app
  #   ports:
  #     - "8080:8080"
  #   restart: always

volumes:
  db_data:
