export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const ERROR_MIDDLEWARE = 'ERROR_MIDDLEWARE';
export const UPLOAD_MP3_SUCCESS = 'UPLOAD_MP3_SUCCESS';
export const GET_OBJECTS_SUCCESS = 'GET_OBJECTS_SUCCESS';
export const GET_OBJECT_DETAIL_SUCCESS = "GET_OBJECT_DETAIL_SUCCESS";
export const GET_URL_AUDIO_SUCCESS = "GET_URL_AUDION_SUCCESS";
export const SET_SPINNER_VISIBILITY = "SET_SPINNER_VISIBILITY";