export const USER_LOGGED_IN= 'USER_LOGGED_IN';
export const USER_SIGNED_IN='USER_SIGNED_IN';
export const TRANSLATE_SUCCESS='TRANSLATE_SUCCESS';
export const ERROR_MIDDLEWARE='ERROR_MIDDLEWARE';
export const SAVE_OBJECT_SUCCESS ='SAVE_OBJECT_SUCCESS';
export const UPLOAD_MP3='UPLOAD_MP3';
export const GET_OBJECTS_SUCCESS='GET_OBJECTS_SUCCESS';